version: '3'

tasks:
  build:
    desc: Build the pt binary
    cmds:
      - go build -o pt main.go

  test:
    desc: Run tests
    cmds:
      - go test ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  serve-docs:
    desc: Serve documentation
    cmds:
      - ./pt run mkdocs serve
