version: '3'

tasks:
  build:
    desc: Build the box binary
    cmds:
      - go build -o box main.go

  test:
    desc: Run tests
    cmds:
      - go test ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  serve-docs:
    desc: Serve documentation
    cmds:
      - ./box run mkdocs serve
